### ISSUE TITLE
General Preprocessing

### ISSUE THREAD

**Issue by aiden200** [aiden200/2D3MF#15]
We need a general preprocessing pipeline that crops, tags the videos as real(-0) or fake(-1). Then generates the .npy files based off of a backbone. Args: data dir, backbone type (small, base, large). 

Please specify a required structure for input. Example:
```
**Data dir**
   Video
       Real
       Fake
   Audio
       Real
       Fake
```

**Comment by aromanusc** [comment]
This is being covered within https://github.com/aiden200/2D3MF/pull/18

The idea is to have an video_backbone (MARLIN) and an audio_backbone, which can be:
- ResNet18: pre-trained to classify 8 emotions with audio data from the RAVDESS dataset
- emotion2vec: https://arxiv.org/abs/2312.15185
- xvectors: https://www.danielpovey.com/files/2018_icassp_xvectors.pdf
- MFCC: default MFCC features

**Comment by aiden200** [comment]
I think this is pretty much implemented
